[package]
name = "pipit-config"
version = "0.1.0"
authors = ["em <e.r.matteson@gmail.com>"]

[[bin]]
name = "main"
path = "src/main.rs"
doc = false

[dependencies]
time = "0.1.36"
toml = "*"
serde_derive = "*"
serde = "*"
itertools = "0.5.9"
error-chain = "0.10.0"