# Every field in a theme file is optional.

shadow = false  # Don't draw shadows around stacked views
borders = "simple"  # Alternatives are "none" and "outset"

[colors]
    # If the value is an array, the first valid color will be used.
    # If the terminal doesn't support custom color,
    # non-base colors will be skipped.
    background = "black"
    shadow     = "white"
    view       = "black"

    primary   = "white"
    secondary = ["red", "#b22222"]
    tertiary  = ["blue", "#4169e1"]

    title_primary   = ["white", "#5f5f5f"]
    title_secondary = ["white", "#303030"]

    highlight          = ["cyan", "#5151bd"]
    highlight_inactive = ["white", "#878787"]
